### ISSUE TITLE
cara dapetin api

### ISSUE THREAD

**Issue by muhamadridwanid** [lintangtimur/ovoid#10]
bisa dibisikin gak gimana dapetin api endpoint beserta parameternya?
pake tools apa?

**Comment by lintangtimur** [comment]
sniff MiTM SSL pinning bypass

**Comment by angaziz** [comment]
Apakah cara tersebut masih bs digunakan @lintangtimur?
Sy sedang mencoba mencari alternatif lain utk get balance, dikarenakan yg sekarang `card_balance (001)` nilainya selalu `0`

**Comment by lintangtimur** [comment]
https://github.com/lintangtimur/ovoid/blob/af97bafa9135789c5d0d920e4c642883ca6da609/src/Ovoid.php#L670

```php
$balance = $o->balance()->getData()->get001();
```

Response
`
object(Stelin\Response\BR001)#11 (3) { ["cardBalance":"Stelin\Response\BR001":private]=> int(22366) ["cardNo":"Stelin\Response\BR001":private]=> string(16) "80005xxxxxx0xxxxxx" ["paymentMethod":"Stelin\Response\BR001":private]=> string(8) "OVO Cash" }
`

**Comment by angaziz** [comment]
I see, terima kasih, ternyata di port nodejs salah pointing berarti: https://github.com/apriady/ovoid-nodejs/blob/master/src/index.js#L75-L81

**Comment by lintangtimur** [comment]
sebenarnya dulu pake itu bisa, tapi kemudian ada update udah beda fungsi lagi. Di lib js sepertinya belum di update.
