### ISSUE TITLE
Get History

### ISSUE THREAD

**Issue by AdzCode** [lintangtimur/ovoid#13]
Ini bisa get history top up ngga?

**Comment by anysz** [comment]
Coba cek
https://github.com/lintangtimur/ovoid#transaction-history
https://github.com/anysz/ovopy#transaction-history

**Comment by lintangtimur** [comment]
@AdzCode bisa
![image](https://user-images.githubusercontent.com/16686825/55543410-32c00f00-56f3-11e9-9804-fd9e21decdce.png)

**Comment by anysz** [comment]
Bisa dilihat dari `transaction_type_id`
