### ISSUE TITLE
Cannot redeclare dd()

### ISSUE THREAD

**Issue by zuramai** [lintangtimur/ovoid#14]
Fatal error: Cannot redeclare dd() (previously declared in /var/www/ovo/vendor/symfony/var-dumper/Resources/functions/dump.php:35) in /var/www/ovo/vendor/lintangtimur/ovoid/src/helper/function.php on line 12

how to fix it?

**Comment by lintangtimur** [comment]
occured because conflict with symfony vardumper, in `function.php` just change that function name
