### ISSUE TITLE
META ID

### ISSUE THREAD

**Issue by falahfr** [lintangtimur/ovoid#15]
bagaimana ya cara mendapakan meta id nya dll 

Karena say coba gagal untuk login 

Respond Test "  Perangkat Kamu telah mencapai batas maksimum untuk login akun OVO. Silahkan email ke cs@ovo.id untuk keterangan lebih lanjut "

**Comment by falahfr** [comment]
untuk meta id sudah berhasil dan sukses login 

Ada contoh script untuk cek history transaksinya gmana masih kurang paham soalnya hehe

**Comment by lintangtimur** [comment]
```php
$ovo = new OVO("token");
echo $ovo->getWalletTransaction(1, 10);
```

baca di README.md
