### ISSUE TITLE
Signature Header Related

### ISSUE THREAD

**Issue by ii64** [lintangtimur/ovoid#16]
Hi, Could you check if this Python repo have what missing from the transfer balance flow? 
[@gramedia-digital-nusantara/ovoclient](https://github.com/gramedia-digital-nusantara/ovoclient/blob/master/src/ovoclient/gateway.py)

Once it working i'll make new update (ovopy), Thanks.

**Comment by lintangtimur** [comment]
`generate_signature` with secret_key? that repo have more information, but idk how to clarify that because from readme, still incomplete lol

**Comment by anysz** [comment]
It should.. probably what they meant with *incomplete* because it is not ready for production release or hardcoding the authentication

**Comment by rizkifani25** [comment]
how about this repo?
@aalfiann/ovo-payment

**Comment by derodevil** [comment]
Anybody has `injected` .apk file? I'll try to analyze the signature

**Comment by lintangtimur** [comment]
> 
> 
> Anybody has `injected` .apk file? I'll try to analyze the signature

i don't have injected apk ,sry

**Comment by ii64** [comment]
Could someone help this issue to get the stacktrace related to balance transfer limitation? It'll help for people to investigate the code easily
https://github.com/lintangtimur/ovoid/blob/279811cb29be27a6a90cf9b62a2c5d3dbf5d6970/src/Ovoid.php#L141-L170

**Comment by derodevil** [comment]
I have tried using  frida+objection but burp/fiddler failed to catch the traffic. the app runs well without showing errors but no traffic are catched

**Comment by ii64** [comment]
virtual `ovo.id.loyalty.network.ApiService`
```java
package ovo.id.loyalty.params.UnlockValidatePayload;
import java.lang.String;
import myobfuscated.a10;
import myobfuscated.re4;
import ovo.id.loyalty.params.UnlockPayload;

public void UnlockValidatePayload.<init>(String p0,String p1,String p2)	//method@0051cf
{
   a10.v0(p0, "trxId", p1, "signature", p2, "securityCode");
   super(0, 0, 3, 0);
   this.trxId = p0;
   this.signature = p1;
   this.setSecurityCode(p2);
}
```

**Comment by ii64** [comment]
>  * karena membutuhkan Signature Header berupa SHA1 untuk memvalidasi TrxId 

Is this what the comment meant?
```java
package myobfuscated.wx7;
import java.lang.String;
import myobfuscated.ve4;
import java.lang.Object;
import java.security.MessageDigest;
import java.nio.charset.Charset;

public final static String wx7.m364e(String p0)	//method@00364e
{
   ve4.f(p0, "text");
   MessageDigest mInstance = MessageDigest.getInstance("SHA-1");
   Charset cName = Charset.forName("iso-8859-1");
   ve4.e(cName, "Charset.forName\(charsetName\)");
   byte[] bBytes = p0.getBytes(cName);
   ve4.e(bBytes, "\(this as java.lang.String\).getBytes\(charset\)");
   mInstance.update(bBytes, 0, p0.length());
   byte[] bdigest = mInstance.digest();
   ve4.e(bdigest, "sha1hash");
   return wx7.m364d(bdigest);
}

```

**Comment by ii64** [comment]
If you try to look at piece of function below (`public final void z59.e0(String p0,String p1,String p2) //method@003a72`)
There's function argument checking whether it is `Parameter specified as non-null is null`, and containing information about what it will be used

```java
....
   ve4.f(p0, "trxId"); // transaction ID
   ve4.f(p1, "amount"); // amount
   ve4.f(p2, "deviceId"); // device ID 
   String str = "||"; // separator
   str = new StringBuilder()+p0+str+p1+str+p2;   // all of them concatenated, trxID + "||" + amount + "||" + deviceID
   try{	
      str = wx7.m364e(str); // function sent above
   }catch(java.security.NoSuchAlgorithmException e-1){	
      vint = 0;
   }catch(java.io.UnsupportedEncodingException e-1){	
   }
....
```

```java
public static void ve4.f(Object p0,String p1)	//method@00cc24
{
   if (p0) {	
      return;
   }	
   NullPointerException nullPointerE = new NullPointerException(ve4.i(p1));
   ve4.l(nullPointerE, ve4.class.getName());
   throw nullPointerE;
}
public static String ve4.i(String p0)	//method@00cc27
{
   StackTraceElement stackTraceEl = Thread.currentThread().getStackTrace()[4];
   return new StringBuilder()+"Parameter specified as non-null is null: method "+stackTraceEl.getClassName()+"."+stackTraceEl.getMethodName()+", parameter "+p0;
}
```

**Comment by lintangtimur** [comment]
> If you try to look at piece of function below (`public final void z59.e0(String p0,String p1,String p2) //method@003a72`)
> There's function argument checking whether it is `Parameter specified as non-null is null`, and containing information about what it will be used
> 
> ```java
> ....
>    ve4.f(p0, "trxId"); // transaction ID
>    ve4.f(p1, "amount"); // amount
>    ve4.f(p2, "deviceId"); // device ID 
>    String str = "||"; // separator
>    str = new StringBuilder()+p0+str+p1+str+p2;   // all of them concatenated, trxID + "||" + amount + "||" + deviceID
>    try{	
>       str = wx7.m364e(str); // function sent above
>    }catch(java.security.NoSuchAlgorithmException e-1){	
>       vint = 0;
>    }catch(java.io.UnsupportedEncodingException e-1){	
>    }
> ....
> ```
> 
> ```java
> public static void ve4.f(Object p0,String p1)	//method@00cc24
> {
>    if (p0) {	
>       return;
>    }	
>    NullPointerException nullPointerE = new NullPointerException(ve4.i(p1));
>    ve4.l(nullPointerE, ve4.class.getName());
>    throw nullPointerE;
> }
> public static String ve4.i(String p0)	//method@00cc27
> {
>    StackTraceElement stackTraceEl = Thread.currentThread().getStackTrace()[4];
>    return new StringBuilder()+"Parameter specified as non-null is null: method "+stackTraceEl.getClassName()+"."+stackTraceEl.getMethodName()+", parameter "+p0;
> }
> ```

someone already made a PR about this, #38, now OVO dont have x86 lib in their APK, only ARM so i cant check it.

**Comment by ii64** [comment]
> someone already made a PR about this, #38, now OVO dont have x86 lib in their APK, only ARM so i cant check it.

Ok any good news?

Which version of OVO that don't have x86 lib? i'm checked the one `3.32.1` and it still there.
![image](https://user-images.githubusercontent.com/26342994/115142215-c52d7400-a06a-11eb-8d25-5a9457c7175f.png)

**Comment by lintangtimur** [comment]
oh good, cant remember what version. But last i checked it doesnt have x86, and cant login using with current endpoint. I will check again

**Comment by lintangtimur** [comment]
Signature header for Bank transfer & OVO solved. #38
