### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by ilham1802** [lintangtimur/ovoid#18]
Maaf bang, ini gimana ya kok ketika composer require lintangtimur/ovoid malah hasil nya 
The requested package lintangtimur/ovoid No version set (parsed as 1.0.0) is satisfiable by lintangtimur/ovoid [No version set (parsed as 1.0.0)] but these conflict with your requirement or minim-stability 

Installation failed, reveeting ./composer.json to iya original content

Mohon bantuannya. Saya masih pemula. terimakasih
![15616739691568060558389630459843](https://user-images.githubusercontent.com/52300201/60304699-5e563c80-9964-11e9-9fc7-501ef1d8fae7.jpg)

**Comment by lintangtimur** [comment]
buat folder kosong, di folder kosong tersebut jalankan perintah
`composer require lintangtimur/ovoid`

![image](https://user-images.githubusercontent.com/16686825/60383526-2eaa5000-9a9c-11e9-8a63-720ce80a6905.png)

**Comment by ilham1802** [comment]
Tetap tidak bisa gan di windows 7. Responnya sama. Bisa tolong diupload ngga file yg kurang nya?

**Comment by lintangtimur** [comment]
> 
> 
> Tetap tidak bisa gan di windows 7. Responnya sama. Bisa tolong diupload ngga file yg kurang nya?

kalo lewat file composer.json? lalu `composer install` sudah dicoba?

buat file composer.json isinya

```json
{
    "require": {
        "lintangtimur/ovoid": "v1.2.3.2"
    }
}
```

lalu jalankan perintah `composer install`

**Comment by ilham1802** [comment]
Coba gan minta nomer WhatsApp nya. Mau kirim gambar sama nanya nanya🙏

**Comment by lintangtimur** [comment]
> 
> 
> Coba gan minta nomer WhatsApp nya. Mau kirim gambar sama nanya nanya🙏

sekalian disini aja

**Comment by kingrootid** [comment]
Error PHP Fatal error: Class 'Stelin\OVOID' not found in /home/xxxx/xxxxx/index.php on line 5
solusinya bagaimana ?
Terima kasih

**Comment by lintangtimur** [comment]
> 
> 
> Error PHP Fatal error: Class 'Stelin\OVOID' not found in /home/xxxx/xxxxx/index.php on line 5
> solusinya bagaimana ?
> Terima kasih

sudah mencoba yang di README.md bagian `example`?

**Comment by kingrootid** [comment]
itu error dari step pertama?

**Comment by lintangtimur** [comment]
run `composer install` di root directory sudah dilakukan? anda install lewat composer atau download(clone) ini repository?

**Comment by ilham1802** [comment]
Gan @lintangtimur coba upload file yang ada di folder vendor gan. Seperti nya masalahnya ada disana. Saya ambil dari composer tidak bisa. Tolong berikan script nya yg di folder gan. Kalo bisa minta nomer whatsapp nya. Terimakasih banyak

**Comment by lintangtimur** [comment]
yang di vendor dapat dari
perintah `composer install`

**Comment by ilham1802** [comment]
Ga bisa gan. Tolong kirim aja file nya ke ilham.febrian80@gmail.com terimakasih

**Comment by komputronika** [comment]
Prosedur install menggunakan composer sudah dijalankan dengan benar.
Tetap masih keluar error seperti ini:

Fatal error: Class 'Stelin\OVOID' not found

**Comment by lintangtimur** [comment]
> 
> 
> Prosedur install menggunakan composer sudah dijalankan dengan benar.
> Tetap masih keluar error seperti ini:
> 
> Fatal error: Class 'Stelin\OVOID' not found

```php
require 'vendor/autoload.php';
use Stelin\OVOID;
```

**Comment by komputronika** [comment]
```php
use Stelin\Ovoid;   // Jangan huruf besar semua

```
Setelah saya utak-atik, ternyata penulisan OVOID nya harus seperti di atas. Setelah itu baru scriptnya lancar jaya.
