### ISSUE TITLE
getWalletTransaction gagal

### ISSUE THREAD

**Issue by febriankrisna** [lintangtimur/ovoid#19]
Responnya begini mas
`{"status":404,"data":null,"message":"Data Not Found!"}`
Barangkali sudah ganti url api nya ya?
Mohon bantuannya kalau ada update lagi.
Terimakasih banyak.

**Comment by lintangtimur** [comment]
Di saya masih bisa, versi OVO terakhir
```php
$ovo = new OVOID($token);
dd($ovo->getWalletTransaction(1,10));
```

Output:
![image](https://user-images.githubusercontent.com/16686825/61117830-9fe8fa80-a4c1-11e9-8399-5e8eb6bc30f6.png)

**Comment by ilham1802** [comment]
Mas @febriankrisna minta file folder vendor dong mas. Tolong di kirim ke ilham.febrian80@gmail.com
Terimakasih

**Comment by febriankrisna** [comment]
Terimakasih mas @lintangtimur , ternyata masalahnya ada di nomor OVO, setelah saya pakai nomor OVO yg lain bisa. Mas @ilham1802 ini folder vendornya [https://drive.google.com/open?id=1mhSoXCb2i9i5aiWacTzFpHXGccuGadUK](https://drive.google.com/open?id=1mhSoXCb2i9i5aiWacTzFpHXGccuGadUK) , saya coba kirim lampiran via email gak bisa.

**Comment by ilham1802** [comment]
Mau nanya mas. Saya dapat result seperti ini
Stelin\Response\WalletTransactionResponse Object ( [status:Stelin\Response\WalletTransactionResponse:private] => 200 [data:Stelin\Response\WalletTransactionResponse:private] => Array ( [0] => stdClass Object ( [pending] => Array ( ) [complete] => Array ( [0] => stdClass Object ( [merchant_invoice] => TRF-c1e7024fd9322e43b3685290e703c8d29db49c08 [merchant_id] => 1 [merchant_name] => OVO [transaction_date] => 2019-07-15 [transaction_time] => 13:56:51 [name] => ILHAM


Nah saya ingin ambil nama dari resultnya. Jadi saya mau ambil ILHAM itu gimana ya mas?

**Comment by lintangtimur** [comment]
> 
> 
> Mau nanya mas. Saya dapat result seperti ini
> Stelin\Response\WalletTransactionResponse Object ( [status:Stelin\Response\WalletTransactionResponse:private] => 200 [data:Stelin\Response\WalletTransactionResponse:private] => Array ( [0] => stdClass Object ( [pending] => Array ( ) [complete] => Array ( [0] => stdClass Object ( [merchant_invoice] => TRF-c1e7024fd9322e43b3685290e703c8d29db49c08 [merchant_id] => 1 [merchant_name] => OVO [transaction_date] => 2019-07-15 [transaction_time] => 13:56:51 [name] => ILHAM
> 
> Nah saya ingin ambil nama dari resultnya. Jadi saya mau ambil ILHAM itu gimana ya mas?

itu didalam array, di loop trus ambil key nya(name)
```php
foreach ($ovo->getWalletTransaction(1, 10)->getData()[0]->complete as $key => $value) {
    dd($value->name);
}
```

**Comment by ilham1802** [comment]
Ok terimakasih mas, kalau transfer ovo ke bank ngga ada yah?

**Comment by lintangtimur** [comment]
> 
> 
> Ok terimakasih mas, kalau transfer ovo ke bank ngga ada yah?

a997eaa0a2346bfa765d1b844c0416ce3e8e2dcd
