### ISSUE TITLE
Transfer ovo

### ISSUE THREAD

**Issue by ilham1802** [lintangtimur/ovoid#20]
Untuk transfer ovo itu ada update atau memang sedang bermasalah ya ? Di saya malah blank hasilnya

**Comment by anysz** [comment]
Error seperti ini? https://github.com/lintangtimur/ovoid/issues/11#issuecomment-478371791

**Comment by ilham1802** [comment]
![Uploading 15636249348963508717720681939155.jpg…]()
Seperti ini gan

**Comment by ilham1802** [comment]
Iya begitu gan. Invalid model

**Comment by lintangtimur** [comment]
> 
> 
> Untuk transfer ovo itu ada update atau memang sedang bermasalah ya ? Di saya malah blank hasilnya

Saya test commit terakhir kemarin untuk transfer OVO bisa 1-2x, untuk transfer ke-3x tidak bisa

**Comment by ilham1802** [comment]
@lintangtimur di saya ngga bisa gan. Bisa minta example code nya ngga? Responnya invalid model dsoalnya

**Comment by ilham1802** [comment]
![15639042478514868472980964036477](https://user-images.githubusercontent.com/52300201/61734971-2a2c3b00-adad-11e9-81f6-c5873439dde2.jpg)

Respon nya begini gan. Tolong bantu. Sukses tf tadi juga respon nya begitu walaupun hanya 2x bisa nya. Cara biar respon nya jadi json gmna ya. Itu respon nya malah failed apa ada yg salah?

**Comment by ichan14** [comment]
gan bisa bantu intalsinya gan

**Comment by ilham1802** [comment]
Sudah bisa gan. Tapi hanya 2x. Ada 1 web mutasi itu dia bisa tf ovo to ovo lebih 2x tanpa error'. Itu gimana ya mas

**Comment by ichan14** [comment]
Gan bisa bantu ane gan ane masib blm jalan

Pada tanggal Sab, 27 Jul 2019 20.56, ilham1802 <notifications@github.com>
menulis:

**Comment by lintangtimur** [comment]
> 
> 
> Sudah bisa gan. Tapi hanya 2x. Ada 1 web mutasi itu dia bisa tf ovo to ovo lebih 2x tanpa error'. Itu gimana ya mas

ada 1 web mutasi? dimana?

**Comment by lintangtimur** [comment]
> 
> 
> gan bisa bantu intalsinya gan

Sudah terinstall composer, lalu jalankan perintah
`composer require lintangtimur/ovoid`

**Comment by ilham1802** [comment]
@lintangtimur ada gan. Saya pakai jasa dia untuk tf ovo to ovo. Bisa lebih 2x tanpa error

**Comment by ilham1802** [comment]
![Screenshot_20190801-225214](https://user-images.githubusercontent.com/52300201/62308167-24baa900-b4af-11e9-9528-0b23f6b6151b.png)
Btw transfer ovo to bank itu respon nya begini. Padahal kemarin kemarin bisa. Apa ovo ada perubahan?

**Comment by lintangtimur** [comment]
> 
> 
> @lintangtimur ada gan. Saya pakai jasa dia untuk tf ovo to ovo. Bisa lebih 2x tanpa error

coba liat mana

**Comment by ilham1802** [comment]
@lintangtimur https://mutasi.atlantic-pedia.co.id dia ada parameter pin juga di tf ovo nya

**Comment by anysz** [comment]
Coba implementasi dulu ntar udh fix w port ke Py

**Comment by ilham1802** [comment]
Yang transfer ovo sama transfer bank selalu begini respon nya sorry unable to handle your request. Sering ngga bisa

**Comment by Krisnasw** [comment]
Udah ada yg solved kah buat transaksi kedua ovo - ke 3 ?

**Comment by lintangtimur** [comment]
> 
> 
> Udah ada yg solved kah buat transaksi kedua ovo - ke 3 ?

belum

**Comment by lintangtimur** [comment]
> 
> 
> Yang transfer ovo sama transfer bank selalu begini respon nya sorry unable to handle your request. Sering ngga bisa

belum saya test lagi, kalau ada waktu akan saya test

**Comment by lintangtimur** [comment]
> 
> 
> Yang transfer ovo sama transfer bank selalu begini respon nya sorry unable to handle your request. Sering ngga bisa

setelah saya test, untuk transfer antar bank percobaan kirim 1 dan 2 masih bisa. Untuk seterusnya butuh signature. Ini sama kasusnya untuk transfer OVO to OVO

**Comment by qya** [comment]
Generate signature dulu baru bisa kirim

**Comment by lintangtimur** [comment]
> 
> 
> Generate signature dulu baru bisa kirim

benar, yang menjadi kendala cara generate signature nya untuk validasi trxid

**Comment by Krisnasw** [comment]
> > Generate signature dulu baru bisa kirim
> 
> benar, yang menjadi kendala cara generate signature nya untuk validasi trxid

Kalo aku sih tiap dia mau trx ovo atau ovo ke bank. always return ke step pertama

**Comment by ilham1802** [comment]
Gan ovo update script jadi tidak berfungsi cara akalin nya gimana ya?

**Comment by lintangtimur** [comment]
> 
> 
> > > Generate signature dulu baru bisa kirim
> > 
> > 
> > benar, yang menjadi kendala cara generate signature nya untuk validasi trxid
> 
> Kalo aku sih tiap dia mau trx ovo atau ovo ke bank. always return ke step pertama

re-auth lagi? pernah saya lakuin reauth sampai dapet token, tapi tetep sama aja ga bisa

**Comment by lintangtimur** [comment]
> 
> 
> Gan ovo update script jadi tidak berfungsi cara akalin nya gimana ya?

maksutnya?

**Comment by ferrisuryadi** [comment]
halo gan, pernah dapat error 415 ga?
response code 415
{"url":"/v1.0/api/auth/customer/genTrxId","method":"POST","remoteAddress":"162.158.43.137","unixtime":1577370137,"message":"otherError"}

**Comment by anysz** [comment]
Terlalu sering transfer?

**Comment by ferrisuryadi** [comment]
Waktu coba di postman bisa sih gan. Entah kayaknya di block ip address kah. Makanya agak sedikit bingung.

Kalo content type kayaknya sudah benar.

**Comment by anysz** [comment]
Cobakan header forwarding, berikut spesifikasi nya
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

**Comment by Krisnasw** [comment]
> > > > Generate signature dulu baru bisa kirim
> > > 
> > > 
> > > benar, yang menjadi kendala cara generate signature nya untuk validasi trxid
> > 
> > 
> > Kalo aku sih tiap dia mau trx ovo atau ovo ke bank. always return ke step pertama
> 
> re-auth lagi? pernah saya lakuin reauth sampai dapet token, tapi tetep sama aja ga bisa

iya di re-auth lagi, bisa kok bang. cuman takutnya kena ban wkwk

**Comment by erzawinsby** [comment]
EZ

**Comment by namdevel** [comment]
https://github.com/namdevel/ovoid-API

**Comment by lintangtimur** [comment]
> 
> 
> https://github.com/namdevel/ovoid-API

Hi, adakah pembeda?

**Comment by namdevel** [comment]
https://ovo-namdevel.nav.co.id

**Comment by lintangtimur** [comment]
> https://ovo-namdevel.nav.co.id

Great work, kenapa `rahasia pribadi` di source nya

**Comment by ardzz** [comment]
capture http requestnya pake apa?

**Comment by ardzz** [comment]
> https://github.com/namdevel/ovoid-API

kalo close source ngapain di share

**Comment by lintangtimur** [comment]
> capture http requestnya pake apa?

Bypass SSL : Frida, Objection
Capture request: Burpsuite

**Comment by ardzz** [comment]
pake emulator apa real engine?
boleh minta tutorial bypass pinningnya?

**Comment by lintangtimur** [comment]
> pake emulator apa real engine?
> boleh minta tutorial bypass pinningnya?

emulator, gak sempet kalo buat video tutor. Di youtube ada.

**Comment by decoderid** [comment]
> > https://github.com/namdevel/ovoid-API
> 
> kalo close source ngapain di share

coba cek yang versi Ruby:

https://github.com/namdevel/ovoid-ruby/blob/master/lib/Ovo.rb

```rb
    # @generateSignature
    def generateSignature()
      # private code unpublished
      return Digest::SHA1.hexdigest(Time.now.to_time.to_s)
    end

    # @unlockAndValidateTrxId
    def unlockAndValidateTrxId(trxId, amount, securityCode)
      payload = {
        'trxId' => trxId,
        'signature' => self.generateSignature(),
        'securityCode' => securityCode
      }
      return @Request.http(Namdevel::Constants::API + '/v1.0/api/auth/customer/unlockAndValidateTrxId', payload, @Headers)
    end
```

padahal dia sendiri yang bilang "RAHASIA" padahal ada di source ruby,, hmm ?

**Comment by ii64** [comment]
Beda ya dengan #16  ?

**Comment by lintangtimur** [comment]
entah itu bisa apa engga, apa sengaja disalahkan
