### ISSUE TITLE
script ga jalan

### ISSUE THREAD

**Issue by herozaro9** [lintangtimur/ovoid#21]
<?php

require 'vendor/autoload.php';

use Stelin\OVOID;
$ovoid = new OVOID($authToken);
dd($ovoid->modelBalance()->getBalance()->getCardNo()('OVO'));

saya coba untuk ambil saldo ga jalan, mohon bimbingannya mastah, saya blom lama belajar PHP

**Comment by lintangtimur** [comment]
paste full code mu disini seperti apa

**Comment by herozaro9** [comment]
sorry, aman ternyata. tadi ga sadar ternyata pake php 5
