### ISSUE TITLE
PHP Recoverable fatal error

### ISSUE THREAD

**Issue by kingrootid** [lintangtimur/ovoid#23]
C:\xampp\htdocs\ovo>php index.php
PHP Recoverable fatal error:  Object of class Stelin\Response\WalletTransactionResponse could not be converted to string in C:\xampp\htdocs\ovo\index.php on line 9

<?php
require 'vendor/autoload.php';
use Stelin\OVOID;
$access_token = "";
$ovoid = new OVOID($access_token);
// echo $ovoid->login2FA('')->getRefId();
// echo $ovoid->login2FAVerify('', '', '')->getUpdateAccessToken();
// echo $ovoid->loginSecurityCode('', '')->getAuthorizationToken();
echo $ovoid->getWalletTransaction(1);

Saya dapat error ketika mengambil mutasinya
adakah solusi ?

**Comment by apriady** [comment]
mungkin bisa tulis full code yang digunakan saat terjadi error tersebut disini 

**nb:jangan tulis informasi yang bersifat rahasia**

**Comment by kingrootid** [comment]
require 'vendor/autoload.php';
use Stelin\OVOID;";
$ovoid = new OVOID($access_token);
// echo $ovoid->login2FA('')->getRefId();
// echo $ovoid->login2FAVerify('', '', '')->getUpdateAccessToken();
// echo $ovoid->loginSecurityCode('', '')->getAuthorizationToken();
$page = 1;
echo $ovoid->getWalletTransaction($page);

**Comment by lintangtimur** [comment]
> 
> 
> require 'vendor/autoload.php';
> use Stelin\OVOID;";
> $ovoid = new OVOID($access_token);
> // echo $ovoid->login2FA('')->getRefId();
> // echo $ovoid->login2FAVerify('', '', '')->getUpdateAccessToken();
> // echo $ovoid->loginSecurityCode('', '')->getAuthorizationToken();
> $page = 1;
> echo $ovoid->getWalletTransaction($page);

Cek ini: https://github.com/lintangtimur/ovoid/issues/19#issuecomment-511652826

**Comment by kingrootid** [comment]
C:\xampp\htdocs\ovo>php index.php
PHP Notice:  Undefined variable: ovo in C:\xampp\htdocs\ovo\index.php on line 9

Notice: Undefined variable: ovo in C:\xampp\htdocs\ovo\index.php on line 9
PHP Fatal error:  Uncaught Error: Call to a member function getWalletTransaction() on null in C:\xampp\htdocs\ovo\index.php:9
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\ovo\index.php on line 9

Fatal error: Uncaught Error: Call to a member function getWalletTransaction() on null in C:\xampp\htdocs\ovo\index.php:9
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\ovo\index.php on line 9

**Comment by lintangtimur** [comment]
sesuaikan variable nya, di contoh comment kan itu pake variable `$ovo`, di code anda variablenya `$ovoid`

**Comment by kingrootid** [comment]
kalau untuk akses via url bagaimana ya ?
ini untuk php command jalannya

**Comment by lintangtimur** [comment]
> 
> 
> kalau untuk akses via url bagaimana ya ?
> ini untuk php command jalannya

maksutnya?
dijalankan lewat web?

**Comment by kingrootid** [comment]
iya dijalankan lewat web gitu

**Comment by lintangtimur** [comment]
> 
> 
> iya dijalankan lewat web gitu

kalo lewat web berarti buat API routing sendiri aja
