### ISSUE TITLE
Sudah tidak berfungsi

### ISSUE THREAD

**Issue by ilham1802** [lintangtimur/ovoid#25]
Gan sekarang sudah ngga berfungsi lagi ya? Kok tiba tiba kemarin langsung error. Pdhalil svlmnya normal normal aja. Coba bantu tes gan

**Comment by lintangtimur** [comment]
yang gak bisa apanya, detail

**Comment by ilham1802** [comment]
![IMG-20190903-WA0070](https://user-images.githubusercontent.com/52300201/64237722-1c7ae100-cf27-11e9-9b93-aee77608f2be.jpg)
Ini contoh punya temen saya. Sepertinya punya saya juga begitu. Semua nya ga bisa mulai dari login, cek transaksi, cek saldo dll. Tolong dibantu gan

**Comment by lintangtimur** [comment]
> 
> 
> ![IMG-20190903-WA0070](https://user-images.githubusercontent.com/52300201/64237722-1c7ae100-cf27-11e9-9b93-aee77608f2be.jpg)
> Ini contoh punya temen saya. Sepertinya punya saya juga begitu. Semua nya ga bisa mulai dari login, cek transaksi, cek saldo dll. Tolong dibantu gan

itu banned ip_addr karena sering login ya? tokennya kan berlaku 1minggu.

saya barusan test juga masih bisa untuk login dapat token.(versi ovo terakhir 2.14.0)

**Comment by ilham1802** [comment]
Login 1x terus udh ga diapa apain. Coba login pake ovo beda malah ga muncul token nya. Blank gitu

**Comment by lintangtimur** [comment]
> 
> 
> Login 1x terus udh ga diapa apain. Coba login pake ovo beda malah ga muncul token nya. Blank gitu

ovo beda maksutnya?

**Comment by ilham1802** [comment]
Akun ovo yang lain. Ga muncul apa apa jadinya

**Comment by apriady** [comment]
Dari info yang diberikan, terlihat bahwa IP address yang anda gunakan sudah di banned oleh OVO.
Kemungkinan banned terjadi karena mereka menganggap ada request yang mencurigakan dari IP yang anda gunakan tersebut.

Solusi yang dapat dicoba :
1. apabila IP tersebut merupakan IP network anda dan anda menggunakan jaringan yg tidak memiliki IP publik statis, bisa dicoba untuk restart modem anda.
2. apabila IP tersebut merupakan IP VM/VPS anda, silahkan create VM/VPS baru agar mendapat IP berbeda atau silahkan gunakan proxy dari provider yang anda percaya

**Comment by ilham1802** [comment]
Oh iya bener gan. Saya pakai hostingn dengan alamat IP lain token nya muncul. Solusi biar ga di banned gimana ya?

**Comment by apriady** [comment]
hindari penggunaan skrip yg dapat menimbulkan kecurigaan pihak ovo.
menurut saya, beberapa hal yg dapat menimbulkan kecurigaan :
- login beberapa nomor berbeda dalam waktu yg berdekatan
- hindari error yg berulang2 dalam rentang waktu tertentu
- gunakan proxy yg berbeda2 untuk setiap nomor

**Comment by ilham1802** [comment]
> hindari penggunaan skrip yg dapat menimbulkan kecurigaan pihak ovo.
> menurut saya, beberapa hal yg dapat menimbulkan kecurigaan :
> 
> * login beberapa nomor berbeda dalam waktu yg berdekatan
> * hindari error yg berulang2 dalam rentang waktu tertentu
> * gunakan proxy yg berbeda2 untuk setiap nomor

Cara memalsukan IP gimana ya? Supaya tidak di banned.

**Comment by ferrisuryadi** [comment]
guys saya ga bisa call loginSecurityCode/verify, errornya 

> {
    "message": "Please update to the latest version of OVO app to enjoy all the features offered by OVO",
    "minAppVersion": "2.9.0",
    "osName": "android",
    "code": 9999
}
apakah agan" ada yg mengalami hal yg sama? thanks
