### ISSUE TITLE
error loginSecurityCode/verify

### ISSUE THREAD

**Issue by ferrisuryadi** [lintangtimur/ovoid#26]
guys saya ga bisa call loginSecurityCode/verify, errornya

{
    "message": "Please update to the latest version of OVO app to enjoy all the features offered by OVO",
    "minAppVersion": "2.9.0",
    "osName": "android",
    "code": 9999
}
apakah agan" ada yg mengalami hal yg sama? thanks.

**Comment by lintangtimur** [comment]
https://github.com/lintangtimur/ovoid/blob/56ede03d2b52c1948002e6cdda1db4dbed9ce207/src/Meta/Meta.php#L13

jika dirubah `META`nya, apakah masih bisa

**Comment by jambispirit** [comment]
> 
> 
> https://github.com/lintangtimur/ovoid/blob/56ede03d2b52c1948002e6cdda1db4dbed9ce207/src/Meta/Meta.php#L13
> 
> jika dirubah `META`nya, apakah masih bisa

Sudah saya coba, namun masih mendapati error yang sama 


Fatal error: Uncaught Stelin\Exception\OvoidException: Please update to the latest version of OVO app to enjoy all the features offered by OVO https://api.ovo.id/v2.0/api/auth/customer/loginSecurityCode/verify in C:\xampp\htdocs\ovo\vendor\lintangtimur\ovoid\src\ParseResponse.php:47 Stack trace: #0 C:\xampp\htdocs\ovo\vendor\lintangtimur\ovoid\src\HTTP\Curl.php(51): Stelin\ParseResponse->__construct('{"message":"Ple...', 'https://api.ovo...') #1 C:\xampp\htdocs\ovo\vendor\lintangtimur\ovoid\src\Ovoid.php(112): Stelin\HTTP\Curl->post('https://api.ovo...', Array, Array) #2 C:\xampp\htdocs\ovo\ceksaldo.php(7): Stelin\OVOID->loginSecurityCode('445566', 'bbc3659f3ae94a9...') #3 {main} thrown in C:\xampp\htdocs\ovo\vendor\lintangtimur\ovoid\src\ParseResponse.php on line 47
