### ISSUE TITLE
Get wallet transaction

### ISSUE THREAD

**Issue by SilentXCodeZ** [lintangtimur/ovoid#27]
Halo gan, pada saat saya mencoba Get wallet Transaction kok result nya begini ya "{"status":401,"data":[],"message":"Unauthorized!"} "
Padahal Authorization token nya sudah benar, kira² kenapa ya gan..? 
Bisa dibantu kah ya kira²..? :)

**Comment by lintangtimur** [comment]
- token mungkin sudah kadaluarsa?

**Comment by SilentXCodeZ** [comment]
Mungkin Codingan saya yg salah ya..? 
Karna saya sudah coba dengan token yg baru juga masih tetap sama, berikut Codingan saya

<?php
class Meta
{
    const APP_ID = 'C7UMRSMFRZ46D9GW9IK7';
    const APP_VERSION = '2.9.0';
    const OS_NAME = 'Android';
    const OS_VERSION = '8.1.0';
    const MAC_ADDRESS = '02:00:00:44:55:66';
    const DEVICE_ID = '5d1fa7f9-fd99-3bae-95d5-67fedb901502';
}

$ovo_url = "https://api.ovo.id/";
$headers = array(
                    "app-id" => Meta::APP_ID,
                    "App-Version" => Meta::APP_VERSION
                );

$auth = "AUTHORIZATION TOKEN SAYA";
        
        
        $temp = ['Authorization'=> $auth];
        $aditionalheader = array_merge($temp, $headers);
        
$ch = curl_init(); 

    curl_setopt($ch, CURLOPT_URL, $ovo_url."wallet/v2/transaction?page=1&limit=10&productType=001");
    curl_setopt($ch, CURLOPT_POST, false);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $aditionalheader);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $auth);
    $output = curl_exec($ch);

    curl_close($ch);      
$json = json_decode($output);
print_r($output);     
?>

Mungkin ada yg salah?
