### ISSUE TITLE
Gimana biar tidak terdeteksi masuk perangkat lain?

### ISSUE THREAD

**Issue by madrish** [lintangtimur/ovoid#29]
Adakah solusi agar tidak terdeteksi masuk ke perangkat lain?

**Comment by anysz** [comment]
Use same device ID (uuid)

**Comment by madrish** [comment]
> Use same device ID (uuid)

bukannya uuid tiap kali login ter-generate?

**Comment by anysz** [comment]
> > Use same device ID (uuid)
> 
> bukannya uuid tiap kali login ter-generate?

Karena itu dia anggap bahwa telah login di device yang baru, kalaupun sama nantinya JWT Auth token nya yg lama bakal expired/invalid

**Comment by madrish** [comment]
> > > Use same device ID (uuid)
> > 
> > 
> > bukannya uuid tiap kali login ter-generate?
> 
> Karena itu dia anggap bahwa telah login di device yang baru, kalaupun sama nantinya JWT Auth token nya yg lama bakal expired/invalid

sy dpt referensi ini. itu kok bisa tanpa terdeteksi masuk perangkat lain ya hmm
ovoapi[dot]arara[dot]tech

**Comment by anysz** [comment]
Sejauh ini selama ngga exceed device login limit ngga pernah dapet notifikasi login di perangkat lain, cobain https://github.com/anysz/ovopy

**Comment by lintangtimur** [comment]
> 
> 
> > > > Use same device ID (uuid)
> > > 
> > > 
> > > bukannya uuid tiap kali login ter-generate?
> > 
> > 
> > Karena itu dia anggap bahwa telah login di device yang baru, kalaupun sama nantinya JWT Auth token nya yg lama bakal expired/invalid
> 
> sy dpt referensi ini. itu kok bisa tanpa terdeteksi masuk perangkat lain ya hmm
> ovoapi[dot]arara[dot]tech

Kalau saya lihat dari responnya, itu bersumber dari sini juga.
Barusan saya test juga masih bisa sampai dapat auth tokennya.
- Login2FA
- Login2FAVerify
- LoginSecurityCode
