### ISSUE TITLE
Transfer Bank & OVO

### ISSUE THREAD

**Issue by erzawinsby** [lintangtimur/ovoid#30]
Mau tanya mas, skrng ada web cekmutasi dari p-store yg bisa TF OVO & bank lebih dari 2x
sistem API sama seperti punya m as nya, pake token

cekmutasi.co.id
barangkali bisa cek dokumentasi api dari web itu, dan bisa melihat alur nya

mereka pake alur begini

TF inquiry Bank/Ovo > Proses TF ke bank/Ovo

**Comment by erzawinsby** [comment]
i found the solutions :p

**Comment by ii64** [comment]
Jadi ?
