### ISSUE TITLE
Authorization Failed

### ISSUE THREAD

**Issue by ardzz** [lintangtimur/ovoid#32]
Sepertinya API update
```
PHP Fatal error:  Uncaught Stelin\Exception\OvoidException: Please update to the latest version of OVO app to enjoy all the features offered by OVO https://api.ovo.id/v2.0/api/auth/customer/loginSecurityCode/verify in /home/ardzz/ovo/vendor/lintangtimur/ovoid/src/ParseResponse.php:47
Stack trace:
#0 /home/ardzz/ovo/vendor/lintangtimur/ovoid/src/HTTP/Curl.php(51): Stelin\ParseResponse->__construct()
#1 /home/ardzz/ovo/vendor/lintangtimur/ovoid/src/Ovoid.php(112): Stelin\HTTP\Curl->post()
#2 /home/ardzz/ovo/ovo.php(10): Stelin\OVOID->loginSecurityCode()
#3 {main}
  thrown in /home/ardzz/ovo/vendor/lintangtimur/ovoid/src/ParseResponse.php on line 47
```

**Comment by lintangtimur** [comment]
ini tricky sih, ganti aja versi `APP` nya
https://github.com/lintangtimur/ovoid/blob/eb21e4cb6983896e2d7dbbba132c795e8dee2c7d/src/Meta/Meta.php#L13

kalau berhasil, push pull request sekalian aja

**Comment by ardzz** [comment]
Mau nanya dong, kalo kita abis switch branch/tags terus mau edit salah satu file ada kaya gini gimana ya?
dari branch master switch tags 1.0.0 mau edit file muncul peringatan gitu

![](https://i.ibb.co/ynT980H/106800849-977168856050658-1645888823493432960-n.jpg)

**Comment by lintangtimur** [comment]
> Mau nanya dong, kalo kita abis switch branch/tags terus mau edit salah satu file ada kaya gini gimana ya?
> dari branch master switch tags 1.0.0 mau edit file muncul peringatan gitu
> 
> ![](https://camo.githubusercontent.com/989b7a7ba86f65bba114372ab1807b1a702e095636042b3eaed622db2ee500ad/68747470733a2f2f692e6962622e636f2f796e54393830482f3130363830303834392d3937373136383835363035303635382d313634353838383832333439333433323936302d6e2e6a7067)

masuk ke branch dimana file itu mau diedit.
