### ISSUE TITLE
Wallet Transaction

### ISSUE THREAD

**Issue by lamboktulus1379** [lintangtimur/ovoid#34]
![image](https://user-images.githubusercontent.com/42629000/93014588-743d3500-f5dc-11ea-9c6d-27ba8b477533.png)

Does this mean there have been no transactions?

**Comment by lintangtimur** [comment]
hm, i think not. Must be from the source `parseResponse.php`

**Comment by lintangtimur** [comment]
saya test barusan masih bisa
