### ISSUE TITLE
can't get refID

### ISSUE THREAD

**Issue by ranggaleoo** [lintangtimur/ovoid#4]
when i use this line code, i always get this error in dirrefent day :
`$ovoid->login2FA($nohp)->getRefId();`

`stdClass Object ( [message] => Perangkat Kamu telah mencapai batas maksimum untuk login akun OVO. Silahkan email ke cs@ovo.id untuk keterangan lebih lanjut. [code] => 1113 )`

**Comment by lintangtimur** [comment]
kejadiannya bagaimana? gagal login atau gimana?

**Comment by ranggaleoo** [comment]
> kejadiannya bagaimana? gagal login atau gimana?

pas mau login

**Comment by lintangtimur** [comment]
saya test tadi masih bisa, sebelum commit terbaru. Apa mungkin login berulang kali?

**Comment by ranggaleoo** [comment]
> saya test tadi masih bisa, sebelum commit terbaru. Apa mungkin login berulang kali?

ah bisa jadi seperti nya, gimana ya cara mengatasi nya, sampe sekarang error nya sama, mencapai batas login, sudah clear cache dan pakai rotate ip padahal

**Comment by lintangtimur** [comment]
kalau login ovo lewat HP masih bisa? mungkin bisa di coba di email cs nya, saya sendiri selama buat wrapper nya test login sampai 3x kalo ga salah

**Comment by ranggaleoo** [comment]
> kalau login ovo lewat HP masih bisa? mungkin bisa di coba di email cs nya, saya sendiri selama buat wrapper nya test login sampai 3x kalo ga salah

berhasil, ternyata di file meta.php nya, saya coba ganti deviceID pake generate dari uniq ID sendiri, dan berhasil, mungkin pesan error muncul di karenakan ovo menganggap perangkat dengan deviceID itu sudah di gunakan banyak akun, sehingga mencapai batas maksimal

cuma sekarang sy ada kendala lagi ketika mau loginSecurityCode, udah masukin accessTOken sama pin code nya dapet pesan seperti ini

`stdClass Object ( [message] => Security Code already set for Customer [code] => 1115 )`

dan sudah di utak atik bingung maksudnya gimana

**Comment by lintangtimur** [comment]
berarti dibuat fungsi sendiri aja ya untuk generate deviceID nya.

security already set cek di #3, ada perubahan endpoint di securityCode

**Comment by ranggaleoo** [comment]
> berarti dibuat fungsi sendiri aja ya untuk generate deviceID nya.
> 
> security already set cek di #3, ada perubahan endpoint di securityCode

okesip berhasil, terimakasih 🙏🏻

**Comment by lintangtimur** [comment]
@ranggaleoo history cek disini 1c73e64f1dc289ddb623b365c5f09a3458b235e6
coba di parsing
