### ISSUE TITLE
Error di PHP 5.6

### ISSUE THREAD

**Issue by fikriisamadd** [lintangtimur/ovoid#43]
Maaf sebelumnya saya saat ini masih memakai php 5.6 dan terjadi error saat get balancemodel
**_PHP Parse error:  syntax error, unexpected '[' in /home/xavircom/public_html/ovo/vendor/lintangtimur/ovoid/src/Response/Model/Profile.php on line 110_**

setelah saya liat script di profile.php
```
public function __construct($data)
    {
        $key = array_keys((array)$data);
        for ($i = 0; $i < count($key); $i++) {
            $keyPriv = $key[$i];
            **$this->$keyPriv = ((array)$data)($key($i));**
        }
    }
```
terdapat error di bagian yang saya tandai
apakah bisa dibantu untuk convert biar ga error di php5.6?

**Comment by lintangtimur** [comment]
di php 5.6 penulisan array dengan `[]` support ga?
setauku di 5.6 penulisan harus `array()`
