### ISSUE TITLE
Bad Request response in login2fa

### ISSUE THREAD

**Issue by raf-lii** [lintangtimur/ovoid#45]
saya mendapatkan respon ketika melakukan post request

`{"url":"/v2.0/api/auth/customer/login2FA","method":"POST","remoteAddress":"xxx.xxx.xxx.xxx","unixtime":1612690628,"message":"badRequest"}"
`

**Comment by lintangtimur** [comment]
saya test masih jalan
di versi ovo 3.32.1 (19 April 2021)
