### ISSUE TITLE
transferOvo error "code":10010001

### ISSUE THREAD

**Issue by g00m00nry0ng** [lintangtimur/ovoid#47]
Punten, kalau dapet respons begini saat menjalankan function transferOvo  kenapa ya?

{"code":10010001,"content":{"present":false},"message":"sorry unable to handle your request"}

**Comment by lintangtimur** [comment]
harus di unlock pakai function ini https://github.com/lintangtimur/ovoid/blob/cf0b7c29f983723b344275356660b9172939343d/src/Ovoid.php#L307
lalu request lagi dengan `function transferOvo`

cek https://github.com/lintangtimur/ovoid/pull/38#issuecomment-740018321

**Comment by g00m00nry0ng** [comment]
ok, bisa, nuhun kang
