### ISSUE TITLE
Error trxId not found

### ISSUE THREAD

**Issue by downygg** [lintangtimur/ovoid#48]
Hallo,
Ovonya sudah update system kah? Saya coba unlock transaksi muncul error **{"message":"trxId not found"}**
Apakah ada solusi untuk issue ini?

Terima kasih.

**Comment by lintangtimur** [comment]
cara unlock udah bener? parameter juga udah bener?

**Comment by downygg** [comment]
parameter sudah benar, dan sudah di unlock dengan benar..
saya coba manual di postman juga hasilnya sama..

**Comment by ii64** [comment]
Sebelumnya pernah berfungsi? Untuk flow nya bagaimana? Transaksi antar OVO atau ke Bank?
Pake trxID yang sama?
https://github.com/lintangtimur/ovoid/blob/908502dc3c669188008673f43144970424e71580/src/Ovoid.php#L155-L170

**Comment by downygg** [comment]
case closed.
Device id saat login ga sama dengan device id saat proses transfer.
btw thanks all.
