### ISSUE TITLE
Transfer OVO tidak berfungsi.

### ISSUE THREAD

**Issue by pasya1912** [lintangtimur/ovoid#49]
Ini kenapa selalu Unable to Handle The Request ya saat Transfer OVO ? sisanya mah lanjay....

**Comment by ii64** [comment]
Kodenya bagaimana

**Comment by pasya1912** [comment]
`sorry unable to handle your request https://api.ovo.id/transfer/direct`
error nya kayak gitu sih...

**Comment by adierwanto** [comment]
transfer sesama ovo masih error "sorry unable to handle your request https://api.ovo.id/v1.0/api/customers/transfer". knpa ya

**Comment by lintangtimur** [comment]
> transfer sesama ovo masih error "sorry unable to handle your request https://api.ovo.id/v1.0/api/customers/transfer". knpa ya

udah di unlock?
