### ISSUE TITLE
Login2FA ga bisa

### ISSUE THREAD

**Issue by adierwanto** [lintangtimur/ovoid#53]
Agar bisa mengakses OVO, Update terlebih dulu aplikasi OVO-mu melalui App Store / Play Store https://api.ovo.id/v2.0/api/auth/customer/login2FA

**Comment by cvkjm** [comment]
sama saya juga gitu kenapa ya?

**Comment by g00m00nry0ng** [comment]
Yes, sama nih. Di saya juga ga bisa dengan message seperti itu.

**Comment by cvkjm** [comment]
Udah diedit di app version tetap g bisa..pliz help

**Comment by lintangtimur** [comment]
sepertinya login OVO sudah migrasi ke V3 #46 , menggunakan enkripsi RSA

**Comment by cvkjm** [comment]
codingnya jadi gimana ya kalo bole tau

**Comment by cvkjm** [comment]
![image](https://user-images.githubusercontent.com/75083007/121717712-b368ca00-cb0b-11eb-8bab-70c26f1de05b.png)

saya coba url ini koq notfound smua ya

**Comment by cvkjm** [comment]
![image](https://user-images.githubusercontent.com/75083007/121718570-a4364c00-cb0c-11eb-982e-43c631df162b.png)

**Comment by lintangtimur** [comment]
V3 pakai ini
https://agw.ovo.id/

**Comment by g00m00nry0ng** [comment]
Newbie setia menunggu contoh kodenya 🙏

**Comment by siska2828** [comment]
Masih gak bisa nih udh pake v3 juga 
![Screenshot_1](https://user-images.githubusercontent.com/50988852/124587789-3ae2f800-de82-11eb-94ce-f4ee3bd6fcc8.jpg)

**Comment by siska2828** [comment]
mohon bantuannya bagi yang ngerti

**Comment by lintangtimur** [comment]
> mohon bantuannya bagi yang ngerti

#46 #54
