### ISSUE TITLE
not supported

### ISSUE THREAD

**Issue by restugbk** [lintangtimur/ovoid#55]
sudah gk support ovo v3 ya mas?

**Comment by ii64** [comment]
wip https://github.com/lintangtimur/ovoid/discussions/46

**Comment by restugbk** [comment]
untuk methodnya seperti cek balance dan cek mutasi apakah sama kaya api v2 sebelumnya??

**Comment by restugbk** [comment]
![image](https://user-images.githubusercontent.com/69737152/125162641-4b151300-e1b3-11eb-9f10-175d80d25e42.png)

bagaimana untuk mendapatkan ini yg saya lingkari dan yg saya garis bawahi

**Comment by lintangtimur** [comment]
https://github.com/lintangtimur/ovoid/discussions/54 coba liat ini

**Comment by restugbk** [comment]
ada utk php kah?

**Comment by lintangtimur** [comment]
belum, bisa coba diimplementasikan sendiri dulu
