### ISSUE TITLE
Ubah Link Verifikasi menjadi otp

### ISSUE THREAD

**Issue by downygg** [lintangtimur/ovoid#58]
saya coba login pake device baru namun otp yg dikirim ke sms berupa link verifikasi melainkan bukan kode otp 4 digit, bagaimanakah cara bypass nya ? thanks

**Comment by lintangtimur** [comment]
kalau link yang dicopy bagian xxxxx nya
https://ovo.id/app/login?code=xxxxxxxxxxxxxxxxxxx

**Comment by Megalomen77** [comment]
Berarti cuman harus di copy yg bagian sehabis code ?
