### ISSUE TITLE
Dokumentasi

### ISSUE THREAD

**Issue by adwidianjaya** [lintangtimur/ovoid#6]
Adakah dokumentasi resmi terkait API OVO? Mungkin nisa dibagikan, untuk memudahkan kontributor nantinya kalau mau membantu mengembangkan repo ini.

**Comment by lintangtimur** [comment]
tidak ada dokumentasi resmi, yang ada hanya di README.md. Dokumentasi yang ada juga berdasarkan hasil snif

**Comment by muhamadridwanid** [comment]
cara sniff nya pake tools apa boskuu
