### ISSUE TITLE
getWalletTransaction

### ISSUE THREAD

**Issue by lintangtimur** [lintangtimur/ovoid#60]
### Discussed in https://github.com/lintangtimur/ovoid/discussions/59

<div type='discussions-op-text'>

<sup>Originally posted by **g00m00nry0ng** September  5, 2021</sup>
ada yg sudah berhasil menggunakan getWalletTransaction? Barusan saya coba masih dapat response error code: 1020 </div>

ini yang riwayat transaksi ya?

**Comment by g00m00nry0ng** [comment]
> ### Discussed in #59
> Originally posted by **g00m00nry0ng** September 5, 2021
> ada yg sudah berhasil menggunakan getWalletTransaction? Barusan saya coba masih dapat response error code: 1020
> 
> ini yang riwayat transaksi ya?

Bener Gan. Belum berhasil juga sampe sekarang. Hehehe

**Comment by gyugie** [comment]
> ### Discussed in #59
> Originally posted by **g00m00nry0ng** September 5, 2021
> ada yg sudah berhasil menggunakan getWalletTransaction? Barusan saya coba masih dapat response error code: 1020
> 
> ini yang riwayat transaksi ya?

iya betul untuk riwayat transaksi
