### ISSUE TITLE
Tidak mendapatkan Kode OTP

### ISSUE THREAD

**Issue by gyugie** [lintangtimur/ovoid#61]
apa ini sudah bisa digunakan ?

 $ovo = new OVOID(null, "87586011-0127-3469-aa2a-6016a68d45f6");
 $login = $ovo->OTP("+62xxxxxxxx")->getData()->getOtp()->getOtpRefId();
 
saya hanya mendapatkan ref id nya saja. tapi tidak mendapatkan kode otp nya / tidak ngirim kode otp ke handphone saya. klo pun ada isinya berbentuk link bukan kode otp

**Comment by lintangtimur** [comment]
link nya adalah kode OTP nya. Di URL nya ada `code=xxxxxxxxxxxxxxxxxxxxx`

**Comment by gyugie** [comment]
oke terimakasih untuk authentikasi nya sudah berhasil

$ovoid = new OVOID($authToken);
$transaction = $ovoid->getWalletTransaction(1, 10); 

response nya error code: 1020     
itu karena apa ya ?

**Comment by kingrootid** [comment]
PHP Deprecated:  Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 55

Deprecated: Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 55
PHP Fatal error:  Uncaught Error: Call to a member function getOtp() on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php:8
Stack trace:
#0 {main}
  thrown in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php on line 8

Fatal error: Uncaught Error: Call to a member function getOtp() on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php:8
Stack trace:
#0 {main}
  thrown in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php on line 8

`<?php
require 'vendor/autoload.php';

use Stelin\OVOID;

$ovo = new OVOID("sss", "2323");
// echo $ovo->OTP("+62....")->getData()->getOtp()->getOtpRefId();
echo $ovo->OTPValidation("+62.....", "sjdhsjd", "232498")->getData()->getOtp()->getOtpToken();
`

**Comment by gyugie** [comment]
@kingrootid 
echo $ovo->OTPValidation("+62.....", "sjdhsjd", "ini return dari step 1 bukan security code")->getData()->getOtp()->getOtpToken();

**Comment by kingrootid** [comment]
> @kingrootid
> echo $ovo->OTPValidation("+62.....", "sjdhsjd", "ini return dari step 1 bukan security code")->getData()->getOtp()->getOtpToken();

dia ada % benar ?

**Comment by kingrootid** [comment]
ketika method **getWalletTransaction**
`PHP Deprecated:  Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 55

Deprecated: Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 55
PHP Warning:  Attempt to read property "status" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 13

Warning: Attempt to read property "status" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 13
PHP Warning:  Attempt to read property "data" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 14

Warning: Attempt to read property "data" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 14
PHP Warning:  Attempt to read property "message" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 15

Warning: Attempt to read property "message" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 15
PHP Fatal error:  Uncaught Error: Object of class Stelin\Response\WalletTransactionResponse could not be converted to string in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php:12
Stack trace:
#0 {main}
  thrown in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php on line 12

Fatal error: Uncaught Error: Object of class Stelin\Response\WalletTransactionResponse could not be converted to string in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php:12
Stack trace:
#0 {main}
  thrown in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php on line 12`

**Comment by gyugie** [comment]
@kingrootid % bukan salah satu respon itu dari teriminal / cmd yang digunakan untuk debugging

jaskhdk1as90123kl%
 hapus % nya

**Comment by kingrootid** [comment]
> @kingrootid % bukan salah satu respon itu dari teriminal / cmd yang digunakan untuk debugging
> 
> jaskhdk1as90123kl%
> hapus % nya

oke sudah bisa login, tinggal get mutasinya aja

**Comment by gyugie** [comment]
> ketika method **getWalletTransaction**
> `PHP Deprecated: Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 55
> 
> Deprecated: Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 55
> PHP Warning: Attempt to read property "status" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 13
> 
> Warning: Attempt to read property "status" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 13
> PHP Warning: Attempt to read property "data" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 14
> 
> Warning: Attempt to read property "data" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 14
> PHP Warning: Attempt to read property "message" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 15
> 
> Warning: Attempt to read property "message" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 15
> PHP Fatal error: Uncaught Error: Object of class Stelin\Response\WalletTransactionResponse could not be converted to string in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php:12
> Stack trace:
> #0 {main}
> thrown in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php on line 12
> 
> Fatal error: Uncaught Error: Object of class Stelin\Response\WalletTransactionResponse could not be converted to string in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php:12
> Stack trace:
> #0 {main}
> thrown in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php on line 12`

yups sama saya juga mengalamai hal ini. mohon bantuan nya kaka @lintangtimur

**Comment by kingrootid** [comment]
> > ketika method **getWalletTransaction**
> > `PHP Deprecated: Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 55
> > Deprecated: Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 55
> > PHP Warning: Attempt to read property "status" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 13
> > Warning: Attempt to read property "status" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 13
> > PHP Warning: Attempt to read property "data" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 14
> > Warning: Attempt to read property "data" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 14
> > PHP Warning: Attempt to read property "message" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 15
> > Warning: Attempt to read property "message" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 15
> > PHP Fatal error: Uncaught Error: Object of class Stelin\Response\WalletTransactionResponse could not be converted to string in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php:12
> > Stack trace:
> > #0 {main}
> > thrown in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php on line 12
> > Fatal error: Uncaught Error: Object of class Stelin\Response\WalletTransactionResponse could not be converted to string in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php:12
> > Stack trace:
> > #0 {main}
> > thrown in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php on line 12`
> 
> yups sama saya juga mengalamai hal ini. mohon bantuan nya kaka @lintangtimur

[#56](https://github.com/lintangtimur/ovoid/discussions/59) disini sih dia pakai v2, tapi di repo nya pakai v3

**Comment by gyugie** [comment]
> > > ketika method **getWalletTransaction**
> > > `PHP Deprecated: Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 55 Deprecated: Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 55 PHP Warning: Attempt to read property "status" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 13 Warning: Attempt to read property "status" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 13 PHP Warning: Attempt to read property "data" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 14 Warning: Attempt to read property "data" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 14 PHP Warning: Attempt to read property "message" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 15 Warning: Attempt to read property "message" on null in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/Response/WalletTransactionResponse.php on line 15 PHP Fatal error: Uncaught Error: Object of class Stelin\Response\WalletTransactionResponse could not be converted to string in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php:12 Stack trace: #0 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php on line 12 Fatal error: Uncaught Error: Object of class Stelin\Response\WalletTransactionResponse could not be converted to string in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php:12 Stack trace: #0 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/ovo/index.php on line 12`
> > 
> > 
> > yups sama saya juga mengalamai hal ini. mohon bantuan nya kaka @lintangtimur
> 
> [#56](https://github.com/lintangtimur/ovoid/discussions/59) disini sih dia pakai v2, tapi di repo nya pakai v3

iya tapi saya coba tidak bisa {"message":"no Route matched with those values"}%
