### ISSUE TITLE
Mndapatkan kode OTP sms

### ISSUE THREAD

**Issue by tenkuken** [lintangtimur/ovoid#62]
$mobilephone = '+62xxxxx';
        $ovo = new OVOID(null, "87586011-0127-3469-aa2a-6016a68d45f6");        
        echo $ovo->OTP($mobilephone)->getData()->getOtp()->getOtpRefId();

Mengapa saya mendapatkan sms 
Klik link verifikasi https://ovo.id/app/login?code=aopsidufaopsdifqw9834faiusdhfaiusdfasdf

Bantuan: 1500696

m9mj4ctIVR8 
??

bagaimana cara mendapatkan kode otp ??

**Comment by lintangtimur** [comment]
kalau berupa link spt diatas, kode otp nya yang dibelakang code=

Ini kode OTP nya
`aopsidufaopsdifqw9834faiusdhfaiusdfasdf`
