### ISSUE TITLE
Ketika Login Menggunakan LINK bukan OTP

### ISSUE THREAD

**Issue by sialexsofficial** [lintangtimur/ovoid#63]
Selmat siang.

Bagaimana  cara login,Ketika saya melakukan tahap 1 saya mendapatkan link verifikasi,Dan bukan kode verifikasi untuk login,Cara mengatasinya bagaimana ya,Sedangkan untuk lanjut ke tahap 2 harus menggunakan OTP. 

Terimakasih

**Comment by apriady** [comment]
kode OTP dapat diganti dengan kode yang ada pada link tersebut.
