### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getOtp() on null

### ISSUE THREAD

**Issue by folcotandiono** [lintangtimur/ovoid#64]
`<?php
require 'vendor/autoload.php';

use Stelin\OVOID;

$ovo = new OVOID(null, "3xxxxx75365095CE");
// $otp = $ovo->OTP("+628xxx7731922")->getData()->getOtp();
// echo $otp;
$otp = "xxxxcba6419efc4f33bb77a58b90d3e443a85d91d44d95e2b495d680cf83a89c";

$otprefid = $ovo->OTP("+628xxx7731922")->getData()->getOtp()->getOtpRefId();
echo $otprefid;

$otptoken = $ovo->OTPValidation("+628xxx7731922", $otprefid, $otp)->getData()->getOtp()->getOtpToken();
echo $otptoken;

echo $ovo->accountLogin("+628xxx7731922", $otprefid, $otptoken, 'xxxx51')->getData()->getAuth()->getAccessToken();
`

**Comment by lintangtimur** [comment]
update ke versi terakhir https://github.com/lintangtimur/ovoid/releases/tag/v3.2
