### ISSUE TITLE
wallet transaction

### ISSUE THREAD

**Issue by folcotandiono** [lintangtimur/ovoid#65]
`
object(Stelin\Response\WalletTransactionResponse)#8 (3) { ["status":"Stelin\Response\WalletTransactionResponse":private]=> int(500) ["data":"Stelin\Response\WalletTransactionResponse":private]=> array(0) { } ["message":"Stelin\Response\WalletTransactionResponse":private]=> string(47) "Maaf transaksi anda sedang tidak dapat diproses" }
`

**Comment by kingrootid** [comment]
sama saya juga mendapatkan error begitu ketika get wallet transaction
