### ISSUE TITLE
code 500

### ISSUE THREAD

**Issue by folcotandiono** [lintangtimur/ovoid#66]
`Fatal error: Uncaught Stelin\Exception\OvoidException: https://api.ovo.id/v1.0/notification/status/count/UNREAD in C:\xampp7\htdocs\ovo\vendor\lintangtimur\ovoid\src\ParseResponse.php:53 Stack trace: #0 C:\xampp7\htdocs\ovo\vendor\lintangtimur\ovoid\src\HTTP\Curl.php(82): Stelin\ParseResponse->__construct('{"code":"500","...', 'https://api.ovo...') #1 C:\xampp7\htdocs\ovo\vendor\lintangtimur\ovoid\src\Ovoid.php(502): Stelin\HTTP\Curl->get('https://api.ovo...', NULL, Array) #2 C:\xampp7\htdocs\ovo\tes.php(26): Stelin\OVOID->unreadHistory() #3 {main}`

**Comment by lintangtimur** [comment]
update ke versi terakhir
https://github.com/lintangtimur/ovoid/releases/tag/v3.2
