### ISSUE TITLE
Whats wrong?

### ISSUE THREAD

**Issue by Naravyb** [lintangtimur/ovoid#7]
Maap pak, saya coba di CI kok hasilnya jadi 
Undefined property: stdClass::$refId, kira2 kenapa ya pak

**Comment by lintangtimur** [comment]
belum pernah juga untuk test di CI, sudah `use Stelin\OVOID` ?
di CI nya sudah install lewat composer untuk `composer install lintangtimur/ovoid` ?
jika tanpa CI apakah tetap bermasalah?

**Comment by Naravyb** [comment]
Saya sudah tambahkan use Stelin\OVOID di class saya pak, namun hasilnya sama saja dan tanpa CI juga sama saja, sebelumnya PHP yang digunakan apa ya?

**Comment by Naravyb** [comment]
A PHP Error was encountered
Severity: Notice

Message: Undefined property: stdClass::$refId

Filename: Response/Login2FAResponse.php

Line Number: 11

Backtrace:

File: C:\xampp2\htdocs\vendor\lintangtimur\ovoid\src\Response\Login2FAResponse.php
Line: 11
Function: _error_handler

File: C:\xampp2\htdocs\vendor\lintangtimur\ovoid\src\ParseResponse.php
Line: 42
Function: __construct

File: C:\xampp2\htdocs\vendor\lintangtimur\ovoid\src\HTTP\Curl.php
Line: 51
Function: __construct

File: C:\xampp2\htdocs\vendor\lintangtimur\ovoid\src\Ovoid.php
Line: 62
Function: post

File: C:\xampp2\htdocs\application\controllers\Auto_jobbing.php
Line: 22
Function: login2FA

File: C:\xampp2\htdocs\index.php
Line: 316
Function: require_once

berikut kesalahannya gan

**Comment by Naravyb** [comment]
Notice: Undefined property: stdClass::$refId in C:\xampp2\htdocs\vendor\lintangtimur\ovoid\src\Response\Login2FAResponse.php on line 11

**Comment by lintangtimur** [comment]
menggunakan PHP 7.2.2
di CI nya sudah diatur di `autoload.php` nya?
[i-have-an-error-in-my-construct](https://stackoverflow.com/questions/32557005/i-have-an-error-in-my-construct)

**Comment by Naravyb** [comment]
saya menggunakan PHP 7,1 namun untuk login, dan sampai step ke tiga semua berjalan lancar solusinya adalah tidak mereturn $data pada bagian __construct di LoginF2AResponse yang sebelumnya adalah

`<?php

namespace Stelin\Response;

class Login2FAResponse
{
    private $refId;

    public function __construct($data)
    {
        $this->refId = $data->refId;
    }

    /**
     * get value of refId
     *
     * @return string
     */
    public function getRefId()
    {
        return $this->refId;
    }
}
`
menjadi
`<?php

namespace Stelin\Response;

class Login2FAResponse
{
    private $refId;

    public function __construct($data)
    {
        return $this->refId = $data;
    }

    /**
     * get value of refId
     *
     * @return string
     */
    public function getRefId()
    {
        return $this->refId;
    }
}
`
finish, and then masalah kembali muncul ketika saya ingin menggunakan fungsi getBalance

```
A PHP Error was encountered
Severity: Notice

Message: Undefined property: stdClass::$childMenu

Filename: Model/Permission.php

Line Number: 17
```

di file Permission.php di bagian model, saya mengubah kembali menjadi 

`foreach ($decoded as $key => $value) {
            $this->_parseChildMenu($value->childMenu);
            $menuName = $value->menuName;
            $this->permission[$menuName] = [
                'id'        => $value->id,
                'isEnabled' => $value->isEnabled,
                'state'     => $value->state,
                'childMenu' => $value->childMenu
            ];
        }` karena stdClass nya bermasalah, nah bagaimana ya agar function __construct bisa return data yang sama semisal `$this->isEnabled = $value->isEnabled`
thanks

**Comment by lintangtimur** [comment]
```php
public function __construct($data)
{
    return $this->refId = $data;
}
```
kalau saya pakai code punyamu malah ga bisa.

setelah saya test di fungsi `getBalance`, error juga muncul di saya, akses variablenya salah yang tadi `$value['childMenu']`menjadi `$value->childMenu`, saya fix terlebih dahulu
