### ISSUE TITLE
getWalletTransaction

### ISSUE THREAD

**Issue by kingrootid** [lintangtimur/ovoid#70]
Ketika menjalankan 
```
$ovo = new OVOID("xxxx", "xxxx");
$transaction = $ovo->getWalletTransaction(1);
```
Muncul Error seperti ini
PHP Deprecated:  Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 53

Deprecated: Required parameter $deviceId follows optional parameter $authToken in /Applications/XAMPP/xamppfiles/htdocs/ovo/vendor/lintangtimur/ovoid/src/OVOID.php on line 53

**Comment by lintangtimur** [comment]
```php
$ovo = new OVOID($token, $deviceId);

print_r($ovo->getWalletTransaction(1));
```

aman ada hasilnya.
Sudah di update ke versi terakhir https://github.com/lintangtimur/ovoid/releases/tag/v3.2 ??
