### ISSUE TITLE
refID null

### ISSUE THREAD

**Issue by downygg** [lintangtimur/ovoid#8]
ketika menjalankan kode : 
require 'vendor/autoload.php';
use Stelin\OVOID;

$ovoid = new OVOID();
$no_hp = 'xxxxxx';
$x = $ovoid->login2FA($no_hp)->getRefId();
var_dump($x);

hasil yang di keluarkan adalah null dan muncul error " Notice: Trying to get property of non-object" , format nomor yang digunakan seperti apa ?

**Comment by lintangtimur** [comment]
Format nomor HP: 08XX

**Comment by downygg** [comment]
masih belum bisa juga, muuncul error ny "Notice: Trying to get property of non-object in C:\xampp\htdocs\xxx\123\vendor\lintangtimur\ovoid\src\Response\Login2FAResponse.php on line 11"

line 11 dari file Login2FAResponse.php adalah : 
$this->refId = $data->refId;

ada solusi kah ?

**Comment by lintangtimur** [comment]
PHP versi berapa?
masalahnya seperti #7

**Comment by downygg** [comment]
pake php v7.1

**Comment by lintangtimur** [comment]
tambahkan code berikut sebelum code refId
```php
dd($data)
```
https://github.com/lintangtimur/ovoid/blob/dbe9b072d95a0e76b6379cc92fda4d3f26b86a6d/src/Response/Login2FAResponse.php#L11

Jadinya
```php
dd($data)
$this->refId = $data->refId;
```

paste hasilnya disini

**Comment by downygg** [comment]
hasil dari var_dump nya NULL

**Comment by lintangtimur** [comment]
https://github.com/lintangtimur/ovoid/blob/dbe9b072d95a0e76b6379cc92fda4d3f26b86a6d/src/ParseResponse.php#L32

dump hasil dari `$chResult`
kalo format HP nya salah responnya akan
```json
{"message":"Mobile number is not registered","code":1053}
```

**Comment by downygg** [comment]
tambahin kode dump nya itu di bagian mana ?

**Comment by lintangtimur** [comment]
> 
> 
> tambahin kode dump nya itu di bagian mana ?

di file ParseResponse.php
taruh code ini,
`dd($chResult)` setelah 
```php
public function __construct($chResult, $url)
```

atau `composer update` saya sudah update ovoid versi 1.2.2, run lagi dan lihat hasilnya

**Comment by downygg** [comment]
> > tambahin kode dump nya itu di bagian mana ?
> 
> di file ParseResponse.php
> taruh code ini,
> `dd($chResult)` setelah
> 
> ```
> public function __construct($chResult, $url)
> ```
> 
> atau `composer update` saya sudah update ovoid versi 1.2.2, run lagi dan lihat hasilnya

result ny bool(false)
