### ISSUE TITLE
Invalid parameters

### ISSUE THREAD

**Issue by andar16** [lintangtimur/ovoid#9]
maaf pak, klo saat generateTrxId muncul keterangan {"message":"Invalid parameters"} itu karna mungkin parameter dari OVO nya yg berubah atau knpa yaa ?

**Comment by lintangtimur** [comment]
sepertinya berubah, nanti saya cek lagi

**Comment by andar16** [comment]
baik pak, trma kasih bnyak

**Comment by lintangtimur** [comment]
generateTrxId sudah saya test dan bisa, untuk transfer muncul error Invalid Model, kalau test langsung dari OVO nya respon:
Hubungi CS Code 400

silahkan update ovoid yang terbaru
`composer update`
